### ISSUE TITLE
Picking up Foliage Crashes

### ISSUE THREAD

**Issue by Lemonzfoyew** [AOCAWOL/BiomesYouGo#12]
For some reason the foliage causes my server to crash upon being picked up.
Was broken with an empty hand.
[Pile_of_dead_leafs_crash.txt](https://github.com/AOCAWOL/BiomesYouGo/files/3638302/Pile_of_dead_leafs_crash.txt)
[Tiny_lilypad_crash.txt](https://github.com/AOCAWOL/BiomesYouGo/files/3638303/Tiny_lilypad_crash.txt)

**Comment by AOCAWOL** [comment]
the dead leaf piles, and lily pads are all being re-worked in 1.6.9 so hopefully, that should solve this issue :)

**Comment by Lemonzfoyew** [comment]
Awesome, wasnt sure if this was a known bug. Any date on 1.6.9's release?

**Comment by AOCAWOL** [comment]
I'm aiming to release 1.6.9 in late October or early September (sorry for the long wait)

**Comment by Lemonzfoyew** [comment]
No problem, I just have a private mod pack that id like to update bugs in. Also just a request it would be awesome if tree capitator could work with your trees. [https://www.curseforge.com/minecraft/mc-mods/treecapitator](Treecapitator).

Thanks for your responses <3
