### ISSUE TITLE
Structure Check Block

### ISSUE THREAD

**Issue by PiordaNautor** [AOCAWOL/BiomesYouGo#13]
I REALLY don't think this should be here. 
![Biome check block](https://user-images.githubusercontent.com/55087535/65380738-97b5f400-dc96-11e9-8d2d-8c681ce2ee87.png)
![Biome check block2](https://user-images.githubusercontent.com/55087535/65380739-98e72100-dc96-11e9-825d-771eed4f45cc.png)
Mind you I'm on survival and didn't know these exist until now.
Here's the f3 menu if you need it.
![check block](https://user-images.githubusercontent.com/55087535/65380740-bc11d080-dc96-11e9-817f-85cb765becf1.png)

**Comment by AOCAWOL** [comment]
Thanks for reporting this! Efforts are being made this update to avoid these issues :)
