### ISSUE TITLE
Suggestion: few biomes idea

### ISSUE THREAD

**Issue by Zack7292** [AOCAWOL/BiomesYouGo#14]
a giant biome (containt giant block with maybe new type of mobs (giant verison of the vanilla ones) and new pickaxe etc... (giant version(they should be better than the original in a way)).

a floral biome in the same type of the flower island biome in biome'o plenty (biome #105 on the wiki), it could be more than one biome and it could countain few declinason with various type of flowers (roses, sunflowers, and a lot more)

a dead biome, should be similar that defilded land in  another style (i want to say it should have the same base but in another style )

a dried biomes: a biome tath countain "dried grass" where everything as ben change to feel more "dried"

a biome tath countains MASSIVe (but when i say MASSIVE i say MASSIVE) trees with giants roots tath come out of it on the ground to be in your way.

tath it, thx for looking :)

**Comment by AOCAWOL** [comment]
Thank you for the ideas! I'll definitely look more into these biome suggestions and see what I can do!

**Comment by Zack7292** [comment]
Cool, Thank!
