### ISSUE TITLE
leaf decay/fire spread and damage

### ISSUE THREAD

**Issue by FloppyDisk01** [AOCAWOL/BiomesYouGo#18]
hello,
I saw a closed issue saying that fire damage on byg's leaf would be a feature on 1.6.9 version of your mod, however i'm in 1.7.0 and i can't burn any leaf of byg's biomes.
Is that a delayed feature or just a bug on my version ?

thank in advance

**Comment by AOCAWOL** [comment]
Hi! They can be set on fire but they won't decay. Leaf Decay and such are a w.i.p due to being more complicated than I used to think.

**Comment by FloppyDisk01** [comment]
okay, thanks for the info
