### ISSUE TITLE
Fir Problems

### ISSUE THREAD

**Issue by Burgersim** [AOCAWOL/BiomesYouGo#20]
Hi there, wanted to let you know, not sure what the problem exactly is but in the newest version of the mod for 1.12 recipes for Fir Wood seem to be broken, I can't craft the bookshelf, Fence, Gate or Wall, or Wood (Bark), also the Sapling seems to be in the ore dictionary as a Stick, is that intentional? Cause the other Saplings don't seem to be. And also the recipe for slabs is weird, since normally it is three plank blocks in a row, like in vanilla minecraft but in my instance its three blocks in a corner formation, so that you could just craft slabs in the 2x2 crafting grid, which I don't really like. Oh and the slabs don't seem to be recognized as "slabWood" in the ore dictionary, which is a bit bad for mod compatibility.

Most of this applies only to Fir though, apart from the slabWood and the slab recipes, they apply to all the different woods, it seems.

I really like the biomes and the blocks though, so I thought I'd try it anyways ^^

**Comment by AOCAWOL** [comment]
Hi! I'll fix Fir Wood thanks for reporting it, as far as slabs go, it's a very messy and not polished block at the moment but I'll be changing the recipe and ore dictionary tag for it :)
