### ISSUE TITLE
Cascading World Gen Lag | Structure Block Eating Ticks

### ISSUE THREAD

**Issue by LeDemmers** [AOCAWOL/BiomesYouGo#21]
Very Noticeable, Way around it for now is pre-generating entire worlds beforehand, so gotta wait about a day or so before playing a world. Other thing to look into would be Structure Blocks, just be sitting around normally they fix structures so we don't have floating trees, but sometimes they generate in the ground, and just tick away eating TPS like its life depended on it.

**Comment by AOCAWOL** [comment]
1.7.1 (releasing tonight) has greatly reduced the cascading world gen lag. As far as StructureCheckBlock goes, there is a new system being worked on for trees in the upcoming updates that will make sure they don't get left behind.
