### ISSUE TITLE
Deobfuscated Minecraft version not ignored by git

### ISSUE THREAD

**Issue by AtlaStar** [AOCAWOL/BiomesYouGo#26]
You should probably update your gitignore to not include the build path since the gradle tasks which create the deobfuscated version of minecraft create it in your build files, meaning you are unintentionally distributing the full deobfuscated version of minecraft to anyone that clones the repo which is a big legal no-no

**Comment by CorgiTaco** [comment]
Good point ima delete this repo anyway

**Comment by CorgiTaco** [comment]
Sorry if I sounded rude btw

**Comment by AtlaStar** [comment]
Oh no worries I didn't take it that way at all, just wanted to point that out so it wouldn't bite sneak up on ya if you got a cease and desist or something because of the accident.
